---
title: "Procesamiento de indicadores de ODS"
output: html_notebook
---
# ODS 1

## 1.1.1
```{r}
library(readxl)
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/1.1.1.xlsx"
destfile <- "X1_1_1.xlsx"
curl::curl_download(url, destfile)
X1_1_1 <- read_excel(destfile, skip = 28)

colnames(X1_1_1) = paste0("ODS1_1_1_",colnames(X1_1_1))

X1_1_1 = X1_1_1[,c(1,10:26)]

names(X1_1_1)
```

```{r}
X1_1_1[,c(2:18)]=lapply(X1_1_1[,c(2:18)], as.numeric)
```

```{r}
X1_1_1$ODS1_1_1_2013= (X1_1_1$ODS1_1_1_2013+ X1_1_1$ODS1_1_1_...12)/2
X1_1_1$ODS1_1_1_2014= (X1_1_1$ODS1_1_1_2014+ X1_1_1$ODS1_1_1_...14)/2
X1_1_1$ODS1_1_1_2015= (X1_1_1$ODS1_1_1_2015+ X1_1_1$ODS1_1_1_...16)/2
X1_1_1$ODS1_1_1_2016= (X1_1_1$ODS1_1_1_2016+ X1_1_1$ODS1_1_1_...18)/2
X1_1_1$ODS1_1_1_2017= (X1_1_1$ODS1_1_1_2017+ X1_1_1$ODS1_1_1_...20)/2
X1_1_1$ODS1_1_1_2018= (X1_1_1$ODS1_1_1_2018+ X1_1_1$ODS1_1_1_...22)/2
X1_1_1$ODS1_1_1_2019= (X1_1_1$ODS1_1_1_2019+ X1_1_1$ODS1_1_1_...24)/2
X1_1_1$ODS1_1_1_2020= (X1_1_1$ODS1_1_1_2020+ X1_1_1$ODS1_1_1_...26)/2
names(X1_1_1)[1]= "DEPARTAMENTO"
```

```{r}
X1_1_1 <- data.frame(X1_1_1[,seq(1,18,2)])

X1_1_1$DEPARTAMENTO= gsub("Lima Metropolitana","LIMA",X1_1_1$DEPARTAMENTO)
X1_1_1$DEPARTAMENTO= gsub("Lima","LIMA PROVINCIAS",X1_1_1$DEPARTAMENTO)
```

## 1.2.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/1.2.1.xlsx"
destfile <- "X1_2_1.xlsx"
curl::curl_download(url, destfile)
X1_2_1 <- read_excel(destfile, skip = 28)

colnames(X1_2_1) = paste0("ODS1_2_1_",colnames(X1_2_1))

X1_2_1 = X1_2_1[,c(1,16:32)]

names(X1_2_1)
```

```{r}
X1_2_1[,c(2:18)]=lapply(X1_2_1[,c(2:18)], as.numeric)
```

```{r}
X1_2_1$ODS1_2_1_2013= (X1_2_1$ODS1_2_1_2013+ X1_2_1$ODS1_2_1_...18)/2
X1_2_1$ODS1_2_1_2014= (X1_2_1$ODS1_2_1_2014+ X1_2_1$ODS1_2_1_...20)/2
X1_2_1$ODS1_2_1_2015= (X1_2_1$ODS1_2_1_2015+ X1_2_1$ODS1_2_1_...22)/2
X1_2_1$ODS1_2_1_2016= (X1_2_1$ODS1_2_1_2016+ X1_2_1$ODS1_2_1_...24)/2
X1_2_1$ODS1_2_1_2017= (X1_2_1$ODS1_2_1_2017+ X1_2_1$ODS1_2_1_...26)/2
X1_2_1$ODS1_2_1_2018= (X1_2_1$ODS1_2_1_2018+ X1_2_1$ODS1_2_1_...28)/2
X1_2_1$ODS1_2_1_2019= (X1_2_1$ODS1_2_1_2019+ X1_2_1$ODS1_2_1_...30)/2
X1_2_1$ODS1_2_1_2020= (X1_2_1$ODS1_2_1_2020+ X1_2_1$ODS1_2_1_...32)/2
names(X1_2_1)[1]= "DEPARTAMENTO"
```

```{r}
X1_2_1 <- data.frame(X1_2_1[,seq(1,18,2)])

X1_2_1$DEPARTAMENTO= gsub("Lima Metropolitana","LIMA",X1_2_1$DEPARTAMENTO)
X1_2_1$DEPARTAMENTO= gsub("Lima","LIMA PROVINCIAS",X1_2_1$DEPARTAMENTO)
```

## 1.3.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/1.3.1.xlsx"
destfile <- "X1_3_1.xlsx"
curl::curl_download(url, destfile)
X1_3_1 <- read_excel(destfile, skip = 7)

colnames(X1_3_1) = paste0("ODS1_3_1_",colnames(X1_3_1))
```

```{r}
X1_3_1[,c(2:14)]=lapply(X1_3_1[,c(2:14)], as.numeric)

names(X1_3_1)[1]= "DEPARTAMENTO"
```

```{r}
X1_3_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X1_3_1$DEPARTAMENTO)
X1_3_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X1_3_1$DEPARTAMENTO)
X1_3_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X1_3_1$DEPARTAMENTO)
```

## 1.4.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/1.4.1.xlsx"
destfile <- "X1_3_1.xlsx"
curl::curl_download(url, destfile)
X1_4_1 <- read_excel(destfile, skip = 7)

colnames(X1_4_1) = paste0("ODS1_4_1_",colnames(X1_4_1))
```

```{r}
X1_4_1[,c(2:8)]=lapply(X1_4_1[,c(2:8)], as.numeric)

names(X1_4_1)[1]= "DEPARTAMENTO"
```

```{r}
X1_4_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X1_4_1$DEPARTAMENTO)
X1_4_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X1_4_1$DEPARTAMENTO)
X1_4_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X1_4_1$DEPARTAMENTO)
```

## Merge
```{r}
ODS_1 = Reduce(function(x, y) merge(x, y, by= "DEPARTAMENTO"), list(X1_1_1, X1_2_1, X1_3_1, X1_4_1))
```

# ODS 2

```{r}
url <- "https://www.inei.gob.pe/media/MenuRecursivo/publicaciones_digitales/Est/Lib1795/cuadros/Cap010.xls"
destfile <- "Cap010.xls"
curl::curl_download(url, destfile)
Cap010 <- read_excel(destfile,sheet = "10.18",skip = 6)

names(Cap010)[c(1,4)]= c("DEPARTAMENTO","2020")
Cap010 =Cap010[,c(1,4)]

Cap010$DEPARTAMENTO =gsub(' [0-9].', '', Cap010$DEPARTAMENTO)
```

```{r}
url <- "https://www.inei.gob.pe/media/MenuRecursivo/publicaciones_digitales/Est/Lib1795/cuadros/Cap010.xls"
destfile <- "Cap010.xls"
curl::curl_download(url, destfile)
Cap010_2 <- read_excel(destfile,sheet = "10.18",skip = 6)

names(Cap010_2)[c(1,7)]= c("DEPARTAMENTO","2020")
Cap010_2 =Cap010_2[,c(1,7)]

Cap010_2$DEPARTAMENTO =gsub(' [0-9].', '', Cap010_2$DEPARTAMENTO)
```

## 2.1.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/2.2.1.xlsx"
destfile <- "X2_2_1.xlsx"
curl::curl_download(url, destfile)
X2_2_1 <- read_excel(destfile, skip = 7)
names(X2_2_1)[1]= "DEPARTAMENTO"

Cap010$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",Cap010$DEPARTAMENTO)
Cap010$DEPARTAMENTO= gsub("Lima Metropolitana","LIMA",Cap010$DEPARTAMENTO)
Cap010$DEPARTAMENTO= gsub("Departamento de Lima","LIMA PROVINCIAS",Cap010$DEPARTAMENTO)

X2_2_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X2_2_1$DEPARTAMENTO)
X2_2_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X2_2_1$DEPARTAMENTO)
X2_2_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X2_2_1$DEPARTAMENTO)

X2_2_1 = merge(X2_2_1, Cap010, by = "DEPARTAMENTO")

names(X2_2_1)[c(2:15)] = paste0("ODS2_2_1_",names(X2_2_1)[c(2:15)])
```

## 2.2.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/2.2.2.xlsx"
destfile <- "X2_2_2.xlsx"
curl::curl_download(url, destfile)
X2_2_2 <- read_excel(destfile, skip = 7)
names(X2_2_2)[1]= "DEPARTAMENTO"
```

```{r}
Cap010_2$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",Cap010_2$DEPARTAMENTO)
Cap010_2$DEPARTAMENTO= gsub("Lima Metropolitana","LIMA",Cap010_2$DEPARTAMENTO)
Cap010_2$DEPARTAMENTO= gsub("Departamento de Lima","LIMA PROVINCIAS",Cap010_2$DEPARTAMENTO)

X2_2_2$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X2_2_2$DEPARTAMENTO)
X2_2_2$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X2_2_2$DEPARTAMENTO)
X2_2_2$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X2_2_2$DEPARTAMENTO)
```

```{r}
X2_2_2 = merge(X2_2_2, Cap010_2, by = "DEPARTAMENTO")

colnames(X2_2_2)[c(2:12)] = paste0("ODS2_2_2_",colnames(X2_2_2)[c(2:12)])

str(X2_2_2)
```

## Merge
```{r}
ODS_2 = Reduce(function(x, y) merge(x, y, by= "DEPARTAMENTO"), list(X2_2_1,X2_2_2))
```

```{r}
ODS_2[,c(2:26)]=lapply(ODS_2[,c(2:26)], as.numeric)
```

# ODS 3

## 3.1.2
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.1.2.xlsx"
destfile <- "X3_1_2.xlsx"
curl::curl_download(url, destfile)
X3_1_2 <- read_excel(destfile, skip = 7)

colnames(X3_1_2) = paste0("ODS3_1_2_",colnames(X3_1_2))
```

```{r}
X3_1_2[,c(2:17)]=lapply(X3_1_2[,c(2:17)], as.numeric)

names(X3_1_2)[1]= "DEPARTAMENTO"
```

```{r}
X3_1_2$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_1_2$DEPARTAMENTO)
X3_1_2$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_1_2$DEPARTAMENTO)
X3_1_2$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_1_2$DEPARTAMENTO)
```

## 3.3.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.3.1.xlsx"
destfile <- "X3_3_1.xlsx"
curl::curl_download(url, destfile)
X3_3_1 <- read_excel(destfile, skip = 7)

colnames(X3_3_1) = paste0("ODS3_3_1_",colnames(X3_3_1))
```

```{r}
X3_3_1[,c(2:38)]=lapply(X3_3_1[,c(2:38)], as.numeric)

names(X3_3_1)[1]= "DEPARTAMENTO"
```

```{r}
X3_3_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_3_1$DEPARTAMENTO)
X3_3_1$DEPARTAMENTO= gsub("Lima","LIMA",X3_3_1$DEPARTAMENTO)
X3_3_1= rbind(X3_3_1, X3_3_1[rep(18),])

X3_3_1[35,1]= "LIMA PROVINCIAS"
```

## 3.3.2
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.3.2.xlsx"
destfile <- "X3_3_2.xlsx"
curl::curl_download(url, destfile)
X3_3_2 <- read_excel(destfile, skip = 7)

colnames(X3_3_2) = paste0("ODS3_3_2_",colnames(X3_3_2))
```

```{r}
X3_3_2[,c(2:23)]=lapply(X3_3_2[,c(2:23)], as.numeric)

names(X3_3_2)[1]= "DEPARTAMENTO"
```

```{r}
X3_3_2$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_3_2$DEPARTAMENTO)
X3_3_2$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_3_2$DEPARTAMENTO)
X3_3_2$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_3_2$DEPARTAMENTO)
```

## 3.3.3
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.3.3.xlsx"
destfile <- "X3_3_3.xlsx"
curl::curl_download(url, destfile)
X3_3_3 <- read_excel(destfile, skip = 7)

colnames(X3_3_3) = paste0("ODS3_3_3_",colnames(X3_3_3))
```

```{r}
X3_3_3[,c(2:39)]=lapply(X3_3_3[,c(2:39)], as.numeric)

names(X3_3_3)[1]= "DEPARTAMENTO"
```

```{r}
X3_3_3$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_3_3$DEPARTAMENTO)
X3_3_3$DEPARTAMENTO= gsub("Lima","LIMA",X3_3_3$DEPARTAMENTO)
X3_3_3= rbind(X3_3_3, X3_3_3[rep(18),])

X3_3_3[33,1]= "LIMA PROVINCIAS"
```

## 3.3.4
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.3.4.xlsx"
destfile <- "X3_3_4.xlsx"
curl::curl_download(url, destfile)
X3_3_4 <- read_excel(destfile, skip = 7)

colnames(X3_3_4) = paste0("ODS3_3_4_",colnames(X3_3_4))
```

```{r}
X3_3_4[,c(2:19)]=lapply(X3_3_4[,c(2:19)], as.numeric)

names(X3_3_4)[1]= "DEPARTAMENTO"
```

```{r}
X3_3_4$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_3_4$DEPARTAMENTO)
X3_3_4$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_3_4$DEPARTAMENTO)
X3_3_4$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_3_4$DEPARTAMENTO)
```

## 3.5.2
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.5.2.xlsx"
destfile <- "X3_5_2.xlsx"
curl::curl_download(url, destfile)
X3_5_2 <- read_excel(destfile, skip = 7)

colnames(X3_5_2) = paste0("ODS3_5_2_",colnames(X3_5_2))
```

```{r}
X3_5_2[,c(2:7)]=lapply(X3_5_2[,c(2:7)], as.numeric)

names(X3_5_2)[1]= "DEPARTAMENTO"
```

```{r}
X3_5_2$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_5_2$DEPARTAMENTO)
X3_5_2$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_5_2$DEPARTAMENTO)
X3_5_2$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_5_2$DEPARTAMENTO)
```

## 3.6.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.6.1.xlsx"
destfile <- "X3_6_1.xlsx"
curl::curl_download(url, destfile)
X3_6_1 <- read_excel(destfile, skip = 7)

colnames(X3_6_1) = paste0("ODS3_6_1_",colnames(X3_6_1))
```

```{r}
X3_6_1[,c(2:8)]=lapply(X3_6_1[,c(2:8)], as.numeric)

names(X3_6_1)[1]= "DEPARTAMENTO"
```

```{r}
X3_6_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_6_1$DEPARTAMENTO)
X3_6_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_6_1$DEPARTAMENTO)
X3_6_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_6_1$DEPARTAMENTO)
```

## 3.7.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.7.1.xlsx"
destfile <- "X3_7_1.xlsx"
curl::curl_download(url, destfile)
X3_7_1 <- read_excel(destfile, skip = 7)

colnames(X3_7_1) = paste0("ODS3_7_1_",colnames(X3_7_1))
```

```{r}
X3_7_1[,c(2:8)]=lapply(X3_7_1[,c(2:8)], as.numeric)

names(X3_7_1)[1]= "DEPARTAMENTO"
```

```{r}
X3_7_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_7_1$DEPARTAMENTO)
X3_7_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_7_1$DEPARTAMENTO)
X3_7_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_7_1$DEPARTAMENTO)
```

## 3.7.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.7.1.xlsx"
destfile <- "X3_7_1.xlsx"
curl::curl_download(url, destfile)
X3_7_1 <- read_excel(destfile, skip = 7)

colnames(X3_7_1) = paste0("ODS3_7_1_",colnames(X3_7_1))
```

```{r}
X3_7_1[,c(2:17)]=lapply(X3_7_1[,c(2:17)], as.numeric)

names(X3_7_1)[1]= "DEPARTAMENTO"
```

```{r}
X3_7_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_7_1$DEPARTAMENTO)
X3_7_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_7_1$DEPARTAMENTO)
X3_7_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_7_1$DEPARTAMENTO)
```

## 3.8.1
```{r}
url <- "https://github.com/ChiaraZamoraM/ODS/raw/main/3.8.1.xlsx"
destfile <- "X3_8_1.xlsx"
curl::curl_download(url, destfile)
X3_8_1 <- read_excel(destfile, skip = 7)

colnames(X3_8_1) = paste0("ODS3_8_1_",colnames(X3_8_1))
```

```{r}
X3_8_1[,c(2:17)]=lapply(X3_8_1[,c(2:17)], as.numeric)

names(X3_8_1)[1]= "DEPARTAMENTO"
```

```{r}
X3_8_1$DEPARTAMENTO= gsub("Prov. Const. del Callao","Callao",X3_8_1$DEPARTAMENTO)
X3_8_1$DEPARTAMENTO= gsub("Provincia de Lima","LIMA",X3_8_1$DEPARTAMENTO)
X3_8_1$DEPARTAMENTO= gsub("Región Lima","LIMA PROVINCIAS",X3_8_1$DEPARTAMENTO)
```

```{r}
ODS_3 = Reduce(function(x, y) merge(x, y, by= "DEPARTAMENTO"), list(X3_1_2,X3_3_1,
                                                                    X3_3_2,X3_3_3,
                                                                    X3_3_4,X3_5_2,
                                                                    X3_6_1,X3_7_1,
                                                                    X3_8_1))
```

# Merge
```{r}
ODS = Reduce(function(x, y) merge(x, y, by= "DEPARTAMENTO"), list(ODS_1,ODS_2, ODS_3))

library(stringi)
ODS$DEPARTAMENTO= stri_trans_general(str = toupper(ODS$DEPARTAMENTO), x)

ODS= ODS[!is.na(ODS$DEPARTAMENTO),]
```

```{r}
ncol(ODS)
```

```{r}
library(reshape2)
library(stringi)
library(tidyverse)
library(lubridate)

ODSTrans= ODS %>% gather( ODS_Ano, Valor, 2:ncol(ODS), na.rm = TRUE, convert = FALSE)

ODSTrans$Ano= sub('.*(\\d{4}).*', '\\1', ODSTrans$ODS_Ano)
ODSTrans$Ano = as.Date(as.character(ODSTrans$Ano), format = "%Y")
ODSTrans$Ano<- year(ODSTrans$Ano)
ODSTrans$ODSNro= str_extract(ODSTrans$ODS_Ano,'[0-9]\\_[0-9]\\_[0-9]')
```

```{r}
library(sf)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(ggrepel)
library(repr)
library(dygraphs)
library(quantmod)
library(rjson)

download.file("https://github.com/ChiaraZamoraM/ODS/raw/main/mapa_Peru/mapa_depas_Lima.zip", 
              destfile = "mapa_depas_Lima.zip" , mode='wb')
unzip("mapa_depas_Lima.zip", exdir = ".")
file.remove("mapa_depas_Lima.zip")

mapa <- st_read("mapa_depas_Lima.shp")

download.file("https://github.com/ChiaraZamoraM/ODS/raw/main/mapa2_Peru/Provincias_Peru.zip", 
              destfile = "Provincias_Peru.zip" , mode='wb')
unzip("Provincias_Peru.zip", exdir = ".")
file.remove("Provincias_Peru.zip")
mapa_prov <- st_read("PROVINCIAS.shp")

mapa_prov$DEPARTAMEN <- ifelse(mapa_prov$PROVINCIA == "LIMA", "LIMA METROPOLITANA", mapa_prov$DEPARTAMEN)
mapa_prov$DEPARTAMEN <- ifelse(mapa_prov$DEPARTAMEN == "LIMA", "LIMA PROVINCIAS", mapa_prov$DEPARTAMEN)
mapa_prov$DEPARTAMEN <- ifelse(mapa_prov$DEPARTAMEN == "LIMA METROPOLITANA", "LIMA", mapa_prov$DEPARTAMEN)

mapa_prov= fortify(mapa_prov)
```

```{r}
mapaODS = merge(mapa, ODSTrans,
              by.x='DEPARTAMEN',by.y="DEPARTAMENTO")

#mapaODS <- mapaODS %>% mutate(centroid = map(geometry, st_centroid), 
 #                             coords = map(centroid, st_coordinates), 
  #                            coords_x = map_dbl(coords, 1), 
   #                           coords_y = map_dbl(coords, 2))

subset1_1_1= subset(mapaODS, ODSNro=="1_1_1" & Ano> 2014)

base1_1_1= ggplot(data = subset1_1_1) + theme_light()
```

```{r}
mapaley1 = base1_1_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa1 = mapaley1 + 
  scale_fill_gradient(low = "lightpink",  high = "firebrick2")+ 
  labs(title = "Incidencia de la pobreza extrema", subtitle = "Indicador 1.1.1") 

mapa1
```

```{r}
ggsave("mapa1_1_1.png")
```
```{r}
ss <- subset(economics, date > as.Date("2006-1-1"))
ggplot(data = ss, aes(x = date, y = pop)) +
geom_line(color = "#FC4E07", size = 2)
```

```{r}
subset1_2_1= subset(mapaODS, ODSNro=="1_2_1" & Ano> 2014)

base1_2_1= ggplot(data = subset1_2_1) + theme_light()
```


```{r}
mapaley2 = base1_2_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa2 = mapaley2 + 
  scale_fill_gradient(low = "lightpink",  high = "firebrick2")+ 
  labs(title = "Incidencia de la pobreza monetaria total", subtitle = "Indicador 1.2.1") 

mapa2
```

```{r}
ggsave("mapa1_2_1.png")
```

```{r}
subset1_3_1= subset(mapaODS, ODSNro=="1_3_1" & Ano> 2014)

base1_3_1= ggplot(data = subset1_3_1) + theme_light()
```

```{r}
mapaley3 = base1_3_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa3 = mapaley3 + 
  scale_fill_gradient(low = "lightpink",  high = "firebrick2")+ 
  labs(title = "Proporción de población de 14 a más años de edad \ncon seguro de pensión", subtitle = "Indicador 1.3.1") 

mapa3
```
```{r}
ggsave("mapa1_3_1.png")
```

```{r}
subset1_4_1= subset(mapaODS, ODSNro=="1_4_1" & Ano> 2014)

base1_4_1= ggplot(data = subset1_4_1) + theme_light()
```

```{r}
mapaley4 = base1_4_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa4 = mapaley4 + 
  scale_fill_gradient(low = "lightpink",  high = "firebrick2")+ 
  labs(title = "Proporción de la población que vive en hogares con \nacceso a servicios básicos de infraestructura", subtitle = "Indicador 1.4.1") 

mapa4
```

```{r}
ggsave("mapa1_4_1.png")
```

```{r}
subset2_2_1= subset(mapaODS, ODSNro=="2_2_1" & Ano> 2014)

base2_2_1= ggplot(data = subset2_2_1) + theme_light()
```


```{r}
mapaley5 = base2_2_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa5 = mapaley5 + 
  scale_fill_gradient(low = "gold",  high = "darkgoldenrod4")+ 
  labs(title = "Tasa de desnutrición crónica entre las niñas y niños menores de 5 años", subtitle = "Indicador 2.2.1") 

mapa5
```

```{r}
ggsave("mapa2_2_1.png")
```

```{r}
subset2_2_2= subset(mapaODS, ODSNro=="2_2_2" & Ano> 2014)

base2_2_2= ggplot(data = subset2_2_2) + theme_light()
```

```{r}
mapaley6 = base2_2_2 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa6 = mapaley6 + 
  scale_fill_gradient(low = "gold",  high = "darkgoldenrod4")+ 
  labs(title = "Tasa de desnutrición aguda entre las niñas y niños menores de 5 años", subtitle = "Indicador 2.2.2") 

mapa6
```

```{r}
ggsave("mapa2_2_2.png")
```

```{r}
subset3_1_2= subset(mapaODS, ODSNro=="3_1_2" & Ano> 2014)

base3_1_2= ggplot(data = subset3_1_2) + theme_light()
```

```{r}
mapaley7 = base3_1_2 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa7 = mapaley7 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Proporción de partos atendidos por personal sanitario especializado", subtitle = "Indicador 3.1.2") 

mapa7
```

```{r}
ggsave("mapa3_1_2.png")
```

```{r}
subset3_3_1= subset(mapaODS, ODSNro=="3_3_1" & Ano> 2014)

base3_3_1= ggplot(data = subset3_3_1) + theme_light()
```

```{r}
mapaley8 = base3_3_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Tasa") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa8 = mapaley8 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Tasa de notificación de casos del virus de la inmunodeficiencia \nhumana (VIH) por cada 100 000 habitantes", subtitle = "Indicador 3.3.1") 

mapa8
```

```{r}
ggsave("mapa3_3_1.png")
```

```{r}
subset3_3_2= subset(mapaODS, ODSNro=="3_3_2" & Ano> 2014)

base3_3_2= ggplot(data = subset3_3_2) + theme_light()
```

```{r}
mapaley9 = base3_3_2 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Tasa") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa9 = mapaley9 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Incidencia de la tuberculosis por cada 100 000 habitantes", subtitle = "Indicador 3.3.2") 

mapa9
```

```{r}
ggsave("mapa3_3_2.png")
```
```{r}
subset3_3_3= subset(mapaODS, ODSNro=="3_3_3" & Ano> 2014)

base3_3_3= ggplot(data = subset3_3_3) + theme_light()
```

```{r}
mapaley10 = base3_3_3 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Tasa") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa10 = mapaley10 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Incidencia de la malaria por cada 100 000 habitantes", subtitle = "Indicador 3.3.3") 

mapa10
```

```{r}
ggsave("mapa3_3_3.png")
```

```{r}
subset3_3_4= subset(mapaODS, ODSNro=="3_3_4" & Ano> 2014)

base3_3_4= ggplot(data = subset3_3_4) + theme_light()
```

```{r}
mapaley11 = base3_3_4 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Tasa") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa11 = mapaley11 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Incidencia de la hepatitis B por cada 100 000 habitantes", subtitle = "Indicador 3.3.4") 

mapa11
```

```{r}
ggsave("mapa3_3_4.png")
```

```{r}
subset3_5_2= subset(mapaODS, ODSNro=="3_5_2" & Ano> 2014)

base3_5_2= ggplot(data = subset3_5_2) + theme_light()
```

```{r}
mapaley12 = base3_5_2 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Tasa") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa12 = mapaley12 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Proporción de personas de 15 y más años de edad que \nconsumieron alguna bebida alcohólica en los últimos 12 meses", subtitle = "Indicador 3.5.2") 

mapa12
```

```{r}
ggsave("mapa3_5_2.png")
```


```{r}
subset3_6_1= subset(mapaODS, ODSNro=="3_6_1" & Ano> 2014)

base3_6_1= ggplot(data = subset3_6_1) + theme_light()
```

```{r}
mapaley13= base3_6_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Tasa") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa13 = mapaley13 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Tasa de fallecidos por accidentes de tránsito", subtitle = "Indicador 3.6.1") 

mapa13
```

```{r}
ggsave("mapa3_6_1.png")
```

```{r}
subset3_7_1= subset(mapaODS, ODSNro=="3_7_1" & Ano> 2014)

base3_7_1= ggplot(data = subset3_7_1) + theme_light()
```

```{r}
mapaley14= base3_6_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa14 = mapaley14 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Proporción de mujeres en edad fértil (de 15 a 49 años) que \npractican la planificación familiar con métodos modernos", subtitle = "Indicador 3.7.1") 

mapa14
```

```{r}
ggsave("mapa3_7_1.png")
```

```{r}
subset3_8_1= subset(mapaODS, ODSNro=="3_8_1" & Ano> 2014)

base3_8_1= ggplot(data = subset3_8_1) + theme_light()
```

```{r}
mapaley15= base3_8_1 +
  geom_sf(aes(fill= Valor)) + labs(fill = "Porcentaje (%)") +
  geom_sf(data = mapa_prov,
          fill = NA) +
  facet_wrap(~Ano)
      
mapa15 = mapaley15 + 
  scale_fill_gradient(low = "darkseagreen1",  high = "forestgreen")+ 
  labs(title = "Proporción de la población con seguro de salud", subtitle = "Indicador 3.8.1") 

mapa15
```

```{r}
ggsave("mapa3_8_1.png")
```

```{r}
write.csv(ODS,"BASE_ODS.csv")
```


# Mapa interactivo
```{r}
library(leaflet)
```

```{r}
pal1 = colorNumeric(palette = "Blues", domain = subset1_1_1$Valor)
```

```{r}
names(subset1_1_1)
```

```{r}
map1_interactive = subset1_1_1  %>% 
  st_transform(crs= "+init=epsg:4326") %>%
  leaflet() %>%
  addProviderTiles(provider= "CartoDB.Positron") %>%
  addPolygons(label= subset1_1_1$DEPARTAMEN,
              stroke = FALSE, 
              smoothFactor =  .5,
              opacity = 1,
              fillOpacity = 0.7,
              fillColor = ~pal1(Valor),
              highlightOptions = highlightOptions(weight = 5,
                                                  fillOpacity= 1,
                                                  color = "black",
                                                  opacity = 1,
                                                  bringToFront = TRUE))%>%

  addLegend("bottomright",
            pal = pal1,
            values = ~Valor,
            title= "Porcentaje (%)",
            opacity= 0.7) 

map1_interactive
```

```{r}
library(htmlwidgets)
saveWidget(map1_interactive, "ODS1_1_1.html")
```
  
```{r}
saveRDS(subset1_1_1, "subset_1_1_1.RDS")
```

```{r}
set = subset(mapaODS, Ano> 2014)

names(set)

set = set[, -4]

ODSSpr= set %>% spread(ODSNro,Valor)

names(ODSSpr)[c(5:10)]= paste0("ODS", names(ODSSpr)[c(5:10)])
```

```{r}
saveRDS(ODSSpr, "ODSSpr.RDS")
```

```{r}
saveRDS(subset1_1_1, "subset_1_1_1.RDS")
```

